name: C/C++ CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Build with lld
        run: |
          mkdir -p .cargo
          echo '[target.x86_64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "zanbil_cc"' >> .cargo/config.toml

      - name: Install dependencies for C++
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make libgtest-dev googletest google-mock

      - name: Configure and build with CMake
        run: |
          mkdir build
          cd build
          cmake -DENABLE_TESTS=ON ..
          cmake --build . -j$(nproc)

      - name: Run tests with CTest
        run: |
          cd build
          ctest -j$(nproc)

      - name: Run zanbil checks
        run: |
          zanbil fmt --check
          zanbil build
          zanbil test