name: C/C++ CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Build with lld
        run: |
          mkdir -p .cargo
          echo '[target.x86_64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "zanbil_cc"' >> .cargo/config.toml
      - run: zanbil fmt --check
      - run: zanbil build
      - run: zanbil test
